name: Repro Dependabot GH Actions Comment Bug
on:
  workflow_dispatch:

jobs:
  repro:
    runs-on: ubuntu-latest
    steps:
      - name: Dummy step
        run: echo "Repro SARIF choosing wrong commit"

      - name: Upload SARIF (pinned older commit)
        uses: github/codeql-action/upload-sarif@51f77329afa6477de8c49fc9c7046c15b9a4e79d # v3.29.5